apiVersion: v2
name: RepoUniqueNormalisedIdentifier
description: A Helm chart for the FastAPI Managed API - RepoUniqueNormalisedIdentifier on Kubernetes
type: application
version: 0.1.0
appVersion: "1.0.0"
